name: MineSouls
version: 1.0a
author: hosttim
main: at.minesouls.MineSouls
api-version: 1.16
depend: [JojokobiUtil]
commands:
  bonfire:
    description: Places Bonfire
    usage: /bonfire <x> <y> <z> <name>
